apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    db: jobvacancy
spec:
  containers:
  - name: db
    image: postgres:10.4
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: pg-passwd
