version: '2'
services:
  password-api:
    image: nicopaez/password-api
    deploy:
      replicas: 2
    expose:
      - "3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - password-api
    ports:
      - "8080:8080"
